export const GET_CURRENCY_REQUEST = 'GET_CURRENCY_REQUEST';
export const GET_CURRENCY_SUCCESS = 'GET_CURRENCY_SUCCESS';
export const GET_RATES_REQUEST = 'GET_RATES_REQUEST';
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS';

export const RAISE_ERROR = 'RAISE_ERROR';
export const SELECT_BASE_CURRENCY = 'SELECT_BASE_CURRENCY';
export const SELECT_TARGET_CURRENCY = 'SELECT_TARGET_CURRENCY';
export const CONVERT_CURRENCY = 'CONVERT_CURRENCY';
export const SET_WALLET_AMOUNT = 'SET_WALLET_AMOUNT';